export const arrColores = [
    'No existe',      'Red ',               'Jujube Red ',
    'Rose Red ',         'Dark Pink ',         'Pink ',
    'Blue ',             'Sky Blue ',          'Light Blue ',
    'Royal Blue ',       'Flesh ',             'Earthy Yellow ',
    'Beige ',            'Khakis ',            'Apple Green ',
    'Yellow ',           'Sand Yellow ',       'Saffron Yellow ',
    'Orange ',           'Brown ',             'Dark Grey ',
    'Light Grey ',       'Black Grey ',        'Brownish Red ',
    'Purple ',           'Light Purple ',      'Mauve ',
    'White ',            'Dark Brown ',        'Army Green ',
    'Dark Skin ',        'Black ',             'Green ',
    'Pale Green ',       'Peppermint Green ',  'Water Blue ',
    'Light Green ',      'Orange Yellow ',     'Bean Paste Red ',
    'Tomato Red ',       'Powder Blue ',       'Pink Purple ',
    'Skin White ',       'Skin Red ',          'Light Skin ',
    'Eggplant ',         'Dark Orange ',       'Peach Pink ',
    'Apricot ',          'Dusky Pink ',        'Dusky Purple ',
    'Grass Green ',      'Egg Yellow ',        'Grey Blue ',
    'Plum Red ',         'Light Grass Green ', 'Light Rose Red ',
    'Dark Powder Blue ', 'Shrimp Flesh ',      'Silvery ',
    'Pale Brown ',       'Lake Blue ',         'Greyish White ',
    'Light Brown ',      'Azure ',             'Pink Green ',
    'Light Lake Blue ',  'Sea Blue ',          'Purplish Red ',
    'Golden ',           'Emerald Green ',     'Coffee ',
    'Greyish Purple ',   'Light Yellow ',      'Cyan ',
    'Dark Grey Blue ',   'Dark Green ',        'Medium Grey ',
    'Medium Purple ',    'Purple Blue ',       'Bean Green ',
    'Blue Green ',       'Bright Blue ',       'Bright White ',
    'Cool Grey ',        'Dark Coffee ',       'Desert Yellow ',
    'Ice Blue ',         'Ink Blue ',          'Light Army Green ',
    'Light Fresh ',      'Olive Green ',       'Pale Red ',
    'Pearl Red ',        'Stone Green ',       'Vermilion ',
    'Medium Orange ',    'Watermelon Red ',    'Dark Blue '
    ]